### ISSUE TITLE
tfswitch is broken

### ISSUE THREAD

**Issue by devopssankar** [warrensbox/terraform-switcher#228] opened 2022-05-11 11:34 UTC
tfswitch fails to find terraform version. 

Issue:
tfswitch 1.1.5
Cannot get list from mirror: https://releases.hashicorp.com/terraform
The provided terraform version does not exist. Try `tfswitch -l` to see all available versions.

Above version is available curl -sL https://releases.hashicorp.com/terraform | grep 1.1.5

**Comment by daniel-huesca** [comment] 2022-05-11 12:01
Apparently, Hashicorp made some changes on their end, so now tfswitch can correctly get the Terraform releases.
Check out https://github.com/warrensbox/terraform-switcher/issues/224

**Comment by lutzwillek-tomtom** [comment] 2022-05-11 12:12
Yes, this issue is a duplicate of https://github.com/warrensbox/terraform-switcher/issues/224

**Comment by warrensbox** [comment] 2022-05-11 14:36
Fixed with release 0.13.1221

**Closed by warrensbox** 2022-05-11 14:36 UTC
